/**
 * Research knowledge base.
 *
 * Every personalization rule in LifeOS traces back to an entry here —
 * official guidelines, meta-analyses, and landmark studies gathered from
 * the web by a multi-agent research sweep and adversarially fact-checked.
 * The Science view renders this registry so users can audit the evidence
 * behind their own targets.
 *
 * strength: guideline > meta-analysis > rct > cohort > expert
 */

export type EvidenceStrength = 'guideline' | 'meta-analysis' | 'rct' | 'cohort' | 'expert';

export interface Citation {
  id: string;
  domain:
    | 'Sleep'
    | 'Physical activity'
    | 'Cardio norms'
    | 'Finance'
    | 'Behavior change'
    | 'Chronotype & work'
    | 'Nutrition & substances'
    | 'Goals & motivation';
  claim: string;
  numbers: string;
  population: string;
  source: string;
  url: string;
  year: number;
  strength: EvidenceStrength;
  /** How LifeOS uses this finding */
  usedFor: string;
}

export const RESEARCH: Citation[] = [
  // ── Sleep ───────────────────────────────────────────────────────────
  {
    id: 'nsf-sleep-duration',
    domain: 'Sleep',
    claim: 'Recommended sleep duration is an age-banded range, not a single number.',
    numbers: 'Teens 14–17y: 8–10h · adults 18–64y: 7–9h · 65+y: 7–8h',
    population: 'General population by age',
    source: 'National Sleep Foundation expert consensus (Hirshkowitz et al., Sleep Health)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/29073412/',
    year: 2015,
    strength: 'guideline',
    usedFor: 'Sleep target range per user age; health pillar scoring',
  },
  {
    id: 'aasm-adult-minimum',
    domain: 'Sleep',
    claim: 'Adults should sleep 7+ hours nightly; 6 or fewer is explicitly inadequate.',
    numbers: '≥7h/night recommended; ≤6h deemed inadequate; <7h linked to weight gain, diabetes, hypertension, impaired immunity',
    population: 'Adults 18–60',
    source: 'AASM & Sleep Research Society consensus statement (Watson et al.)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/26039963/',
    year: 2015,
    strength: 'guideline',
    usedFor: 'Hard floor for the sleep score curve',
  },
  {
    id: 'sleep-regularity-mortality',
    domain: 'Sleep',
    claim: 'Sleep regularity predicts mortality more strongly than sleep duration.',
    numbers: 'Most- vs least-regular quintiles: 20–48% lower all-cause mortality, 16–39% lower cancer mortality, 22–57% lower cardiometabolic mortality',
    population: '60,977 UK Biobank adults',
    source: 'Windred et al., Sleep',
    url: 'https://academic.oup.com/sleep/article/47/1/zsad253/7280269',
    year: 2024,
    strength: 'cohort',
    usedFor: 'Bedtime-consistency scoring weighs regularity, not just duration',
  },
  {
    id: 'chronic-restriction-deficit',
    domain: 'Sleep',
    claim: 'Chronic mild sleep restriction accumulates cognitive debt that never plateaus — and people stop noticing it.',
    numbers: '6h/night × 14 nights ≈ the lapse rate of 1–2 nights of total sleep deprivation; subjective sleepiness ratings flatline while performance keeps falling',
    population: 'Controlled 14-day dose-response RCT',
    source: 'Van Dongen et al., Sleep',
    url: 'https://pubmed.ncbi.nlm.nih.gov/12683469/',
    year: 2003,
    strength: 'rct',
    usedFor: 'Crunch-mode sleep floor; "you can\'t feel the deficit" framing',
  },
  {
    id: 'short-sleep-calories',
    domain: 'Sleep',
    claim: 'Partial sleep loss increases next-day energy intake without increasing expenditure.',
    numbers: '+385 kcal/day net intake after restricted sleep, skewed toward fat; no change in energy burned',
    population: 'Meta-analysis, 11 studies, n=172',
    source: 'Al Khatib et al., European Journal of Clinical Nutrition',
    url: 'https://pubmed.ncbi.nlm.nih.gov/27804960/',
    year: 2017,
    strength: 'meta-analysis',
    usedFor: 'Cross-pillar sleep→nutrition/spending pattern probes and briefing copy',
  },
  {
    id: 'weekend-catchup-incomplete',
    domain: 'Sleep',
    claim: 'Weekend catch-up sleep does not undo the metabolic damage of weekday restriction.',
    numbers: 'Ad-libitum weekend recovery failed to prevent reduced insulin sensitivity and weight gain from restricted weekdays',
    population: 'Adults in controlled lab study',
    source: 'Depner et al., Current Biology',
    url: 'https://www.cell.com/current-biology/fulltext/S0960-9822(19)30098-3',
    year: 2019,
    strength: 'rct',
    usedFor: 'Scores consistent sleep above binge-and-repay patterns',
  },
  {
    id: 'nap-guidance',
    domain: 'Sleep',
    claim: 'Short early-afternoon naps restore alertness without grogginess; long naps risk sleep inertia.',
    numbers: '10–20 min ideal (NASA 26-min nap: +54% alertness, +34% performance); >30 min risks 30–60 min of sleep inertia; best window ~1–3 PM',
    population: 'Shift workers, pilots, adults',
    source: 'NASA Ames fatigue research (Rosekind et al.); sleep-medicine consensus',
    url: 'https://ntrs.nasa.gov/citations/19950006379',
    year: 1995,
    strength: 'expert',
    usedFor: 'Nap recommendations for shift workers and new parents',
  },
  {
    id: 'jet-lag-adaptation',
    domain: 'Sleep',
    claim: 'Circadian re-entrainment after travel is direction-dependent — eastward is harder.',
    numbers: 'Westward ~1.5h/day adjustment, eastward ~1h/day; well-timed light exposure can compress adaptation substantially',
    population: 'Travelers and lab-shifted subjects',
    source: 'Circadian medicine reviews (Eastman & Burgess, Sleep Medicine Clinics)',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2829880/',
    year: 2009,
    strength: 'expert',
    usedFor: 'Travel-mode recommendations (light timing, direction-aware expectations)',
  },

  // ── Physical activity ───────────────────────────────────────────────
  {
    id: 'who-activity-2020',
    domain: 'Physical activity',
    claim: 'Adults: 150–300 min/week moderate aerobic activity plus 2+ strength days. 65+: add balance training 3+ days/week.',
    numbers: '150–300 min moderate (or 75–150 vigorous)/wk · strength ≥2 d/wk · 65+: multicomponent balance ≥3 d/wk to prevent falls',
    population: 'Adults 18–64 and 65+',
    source: 'WHO Guidelines on Physical Activity and Sedentary Behaviour',
    url: 'https://www.who.int/publications/i/item/9789240015128',
    year: 2020,
    strength: 'guideline',
    usedFor: 'Active-minutes and strength targets; balance emphasis for 65+',
  },
  {
    id: 'paluch-steps-2022',
    domain: 'Physical activity',
    claim: 'The mortality benefit of steps plateaus at an age-dependent level — 10,000 is not a universal target.',
    numbers: 'Plateau ~6,000–8,000 steps/day for 60+ · ~8,000–10,000 for <60 · 47,471 adults, 3,013 deaths, 7.1y median follow-up',
    population: '15 international cohorts',
    source: 'Paluch et al., The Lancet Public Health',
    url: 'https://www.thelancet.com/journals/lanpub/article/PIIS2468-2667(21)00302-9/fulltext',
    year: 2022,
    strength: 'meta-analysis',
    usedFor: 'Age-adjusted daily step targets',
  },
  {
    id: 'steps-7000',
    domain: 'Physical activity',
    claim: '7,000 steps/day captures most of the benefit across mortality, CVD, cancer, dementia, and depression.',
    numbers: '7,000 vs 2,000 steps/day: −47% all-cause mortality, −25% CVD incidence, −38% dementia, −22% depression, −28% falls; curve steepest at the low end',
    population: '~160,000 adults across 57 studies',
    source: 'Ding et al., The Lancet Public Health',
    url: 'https://www.thelancet.com/journals/lanpub/article/PIIS2468-2667(25)00164-1/fulltext',
    year: 2025,
    strength: 'meta-analysis',
    usedFor: '"Some is better than none" framing; beginner step targets',
  },
  {
    id: 'acsm-progression',
    domain: 'Physical activity',
    claim: 'Training progression scales with experience: novices thrive on 2–3 full-body days; advanced trainees need periodized volume.',
    numbers: 'Novice 2–3 d/wk @ 70–85% 1RM, 8–12 reps · intermediate 3–4 d/wk · advanced 4–5 d/wk periodized up to 100% 1RM',
    population: 'Healthy adults by training status',
    source: 'ACSM Position Stand: Progression Models in Resistance Training',
    url: 'https://pubmed.ncbi.nlm.nih.gov/19204579/',
    year: 2009,
    strength: 'guideline',
    usedFor: 'Fitness-level-specific training recommendations',
  },
  {
    id: 'hrv-guided-training',
    domain: 'Physical activity',
    claim: 'Scheduling hard sessions by daily HRV beats fixed programs.',
    numbers: 'HRV-guided vs predefined training: +2.84 mL/kg/min VO2max mean difference in meta-analysis',
    population: 'Trained and amateur endurance athletes',
    source: 'Meta-analysis of HRV-guided training RCTs (Frontiers in Physiology)',
    url: 'https://www.frontiersin.org/articles/10.3389/fphys.2021.735265/full',
    year: 2021,
    strength: 'meta-analysis',
    usedFor: 'Recovery-gated training recommendations ("green-light days")',
  },
  {
    id: 'neck-check',
    domain: 'Physical activity',
    claim: 'The "neck check": above-the-neck symptoms permit light exercise; fever or below-the-neck symptoms mean rest.',
    numbers: 'Fever ≥100.4°F (38°C), chest congestion, body aches → no training until fever-free ≥24h without medication',
    population: 'Adults with acute illness',
    source: 'American College of Sports Medicine guidance',
    url: 'https://www.acsm.org/blog-detail/acsm-certified-blog/2019/12/23/exercise-during-cold-flu-season',
    year: 2019,
    strength: 'expert',
    usedFor: 'Sick-mode recommendation logic',
  },
  {
    id: 'sedentary-breaks',
    domain: 'Physical activity',
    claim: 'Interrupting sitting with 5 minutes of light walking every 30 minutes markedly blunts post-meal metabolic damage.',
    numbers: '5-min light walk / 30 min sitting: glucose response −28%, insulin −37%; beats standing breaks',
    population: 'Desk-working adults, crossover trials',
    source: 'Duran et al., Medicine & Science in Sports & Exercise',
    url: 'https://pubmed.ncbi.nlm.nih.gov/36631190/',
    year: 2023,
    strength: 'rct',
    usedFor: 'Movement-snack nudges for desk-bound work patterns',
  },
  {
    id: 'postpartum-return',
    domain: 'Physical activity',
    claim: 'Postpartum exercise return is staged by recovery, not the calendar.',
    numbers: 'Pelvic-floor work: immediately · gentle 30-min walks: within days · graded training after medical clearance (~6wk, longer post-cesarean)',
    population: 'Postpartum women',
    source: 'ACOG Committee Opinion 804',
    url: 'https://www.acog.org/clinical/clinical-guidance/committee-opinion/articles/2020/04/physical-activity-and-exercise-during-pregnancy-and-the-postpartum-period',
    year: 2020,
    strength: 'guideline',
    usedFor: 'New-parent mode training guidance',
  },

  // ── Cardio norms ────────────────────────────────────────────────────
  {
    id: 'rhr-norms',
    domain: 'Cardio norms',
    claim: 'Normal resting HR is 60–100 bpm; women run a few bpm higher than men; elevated RHR independently predicts mortality.',
    numbers: 'Wearable data (n=92,457): mean 65 bpm, women +2–7 bpm vs men · each +10 bpm: +9% all-cause mortality risk · athletes 40–60 bpm',
    population: 'General adult population',
    source: 'AHA; Quer et al., PLOS ONE; Zhang et al. meta-analysis (CMAJ)',
    url: 'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0227709',
    year: 2020,
    strength: 'meta-analysis',
    usedFor: 'RHR context bands (sex-aware) in dashboard and briefing copy',
  },
  {
    id: 'hrv-individual',
    domain: 'Cardio norms',
    claim: 'HRV varies ~4× between healthy people and declines with age — only within-person trends are meaningful.',
    numbers: 'Healthy-adult RMSSD mean ~42ms but range ~19–75ms across studies; declines steeply from 2nd to 6th decade; athletes ~20–30% higher',
    population: 'Healthy adults, pooled normative studies',
    source: 'Nunan et al., PACE (systematic review of short-term HRV norms)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/20663071/',
    year: 2010,
    strength: 'meta-analysis',
    usedFor: 'HRV is scored against the user\'s own baseline, never a universal number',
  },
  {
    id: 'cdc-weight-loss',
    domain: 'Cardio norms',
    claim: 'Gradual weight loss of 1–2 lb/week is more likely to be maintained; even 5–10% loss is clinically meaningful.',
    numbers: '1–2 lb/week via ~500 kcal/day deficit; 7% loss + 150 min/wk activity cut diabetes incidence 58% (DPP trial)',
    population: 'Adults with overweight/obesity',
    source: 'CDC Healthy Weight guidance; Diabetes Prevention Program (NEJM)',
    url: 'https://www.cdc.gov/healthy-weight-growth/losing-weight/index.html',
    year: 2023,
    strength: 'guideline',
    usedFor: 'Safe weight-loss band and simulator timelines',
  },
  {
    id: 'bmi-limits',
    domain: 'Cardio norms',
    claim: 'BMI cutoffs are population screening tools with known limits — they miss muscle/fat composition and shift across ethnic groups.',
    numbers: 'Standard: overweight ≥25, obese ≥30 · WHO Asian action points: elevated risk ≥23, high risk ≥27.5',
    population: 'Global populations',
    source: 'WHO Expert Consultation, The Lancet',
    url: 'https://pubmed.ncbi.nlm.nih.gov/14726171/',
    year: 2004,
    strength: 'guideline',
    usedFor: 'Weight guidance framed by trend + health markers, not BMI alone',
  },
  {
    id: 'bp-lifestyle',
    domain: 'Cardio norms',
    claim: 'Each lifestyle lever lowers blood pressure by a quantifiable amount.',
    numbers: 'DASH diet ~−11 mmHg systolic · ~−1 mmHg per kg lost · exercise, sodium reduction, alcohol moderation ~−4–5 mmHg each',
    population: 'Adults with elevated BP',
    source: '2017 ACC/AHA Hypertension Guideline',
    url: 'https://www.ahajournals.org/doi/10.1161/HYP.0000000000000065',
    year: 2017,
    strength: 'guideline',
    usedFor: 'Prioritizing lifestyle recommendations by expected effect size',
  },

  // ── Finance ─────────────────────────────────────────────────────────
  {
    id: 'fifty-thirty-twenty',
    domain: 'Finance',
    claim: 'The 50/30/20 rule: ≤50% of after-tax income to needs, ~30% to wants, ≥20% to savings and debt payoff.',
    numbers: '50% needs / 30% wants / 20% savings+debt, on after-tax income',
    population: 'General budgeting heuristic',
    source: 'Warren & Tyagi, "All Your Worth" (popularized by CFPB)',
    url: 'https://www.consumerfinance.gov/about-us/blog/budgeting-how-to-create-a-budget-and-stick-with-it/',
    year: 2005,
    strength: 'expert',
    usedFor: 'Deriving the weekly discretionary budget from income',
  },
  {
    id: 'emergency-fund',
    domain: 'Finance',
    claim: 'Emergency funds should be sized to the situation: a starter buffer first, then months of expenses — more for irregular income.',
    numbers: 'Starter $500–1,000 · baseline 3–6 months · 6–12 months for irregular/self-employed income · Vanguard: ≥$2,000 buffer → +21% financial wellbeing',
    population: 'US households',
    source: 'CFPB; Vanguard emergency-savings research',
    url: 'https://www.consumerfinance.gov/an-essential-guide-to-building-an-emergency-fund/',
    year: 2024,
    strength: 'guideline',
    usedFor: 'Emergency-fund sizing per income stability and life stage',
  },
  {
    id: 'small-buffer-hardship',
    domain: 'Finance',
    claim: 'Even a few hundred dollars of buffer measurably protects low-income households from hardship.',
    numbers: '$250–749 in savings → 28% lower probability of missing a housing payment vs <$250',
    population: 'Low-income US families',
    source: 'Urban Institute, "Thriving Residents" savings & hardship analysis',
    url: 'https://www.urban.org/research/publication/how-do-families-cope-financial-shocks',
    year: 2016,
    strength: 'cohort',
    usedFor: 'Starter-fund recommendations for students/low-income users',
  },
  {
    id: 'fidelity-milestones',
    domain: 'Finance',
    claim: 'Age-based retirement milestones: salary multiples saved by each age, on a ~15% savings rate started at 25.',
    numbers: '1x by 30 · 3x by 40 · 6x by 50 · 8x by 60 · 10x by 67 · rate ladder: 15% from 25, 18% from 30, 23% from 35',
    population: 'US workers targeting retirement at 67',
    source: 'Fidelity Investments retirement guidelines',
    url: 'https://www.fidelity.com/viewpoints/retirement/how-much-do-i-need-to-retire',
    year: 2024,
    strength: 'expert',
    usedFor: 'Life-stage savings-rate targets and wealth pillar context',
  },
  {
    id: 'equity-returns',
    domain: 'Finance',
    claim: 'US equities returned ~9.7% nominal (6.6% real) 1900–2024, but forward-looking models project less — planners should assume moderate returns.',
    numbers: 'History: 9.7% nominal / 6.6% real (DMS 1900–2024) · Vanguard 10y forward forecast: 3.9–5.9% nominal · LifeOS models 6% nominal as a middle path',
    population: 'Long-horizon investors',
    source: 'Dimson-Marsh-Staunton Global Returns Yearbook (UBS); Vanguard Capital Markets Model',
    url: 'https://www.ubs.com/global/en/investment-bank/global-markets/global-investment-returns-yearbook.html',
    year: 2025,
    strength: 'cohort',
    usedFor: 'Simulator compound-growth assumption (6% nominal)',
  },
  {
    id: 'safe-withdrawal',
    domain: 'Finance',
    claim: 'The 4% rule survives most 30-year retirements historically; forward-looking estimates hover slightly below.',
    numbers: 'Bengen SAFEMAX ~4.15% · Trinity 30y success: 95–98% at 50–75% stocks · Morningstar base-case starting rate 2021–2025: 3.3–4.0%',
    population: 'Retirees with balanced portfolios',
    source: 'Bengen (J. Financial Planning); Trinity study; Morningstar State of Retirement Income',
    url: 'https://www.morningstar.com/retirement/whats-safe-withdrawal-rate-today',
    year: 2025,
    strength: 'expert',
    usedFor: 'Withdrawal-discipline framing for retired personas',
  },
  {
    id: 'debt-priority',
    domain: 'Finance',
    claim: 'Debt-vs-invest priority: employer match first, then starter fund, then debt above ~6% APR, then invest.',
    numbers: '401(k) match ≈ instant 50–100% return · credit cards (~20%+ APR) always beat expected market returns · avalanche is interest-optimal',
    population: 'US savers with debt',
    source: 'Fidelity debt-vs-invest hierarchy',
    url: 'https://www.fidelity.com/viewpoints/personal-finance/pay-down-debt-vs-save',
    year: 2024,
    strength: 'expert',
    usedFor: 'Ordering wealth recommendations when debt exists',
  },

  // ── Behavior change ─────────────────────────────────────────────────
  {
    id: 'lally-habits',
    domain: 'Behavior change',
    claim: 'New habits take a median ~66 days to become automatic — and missing a single day doesn\'t matter.',
    numbers: 'Median 66 days to plateau automaticity; range 18–254; one missed repetition had no material effect on formation',
    population: '96 adults forming a daily habit',
    source: 'Lally et al., European Journal of Social Psychology',
    url: 'https://onlinelibrary.wiley.com/doi/10.1002/ejsp.674',
    year: 2010,
    strength: 'cohort',
    usedFor: 'Habit-streak framing; broken-streak forgiveness in coaching copy',
  },
  {
    id: 'implementation-intentions',
    domain: 'Behavior change',
    claim: '"If-then" plans (when, where, how) substantially raise goal attainment.',
    numbers: 'd = 0.65 across 94 independent tests (~8,000 participants); strongest for hard-to-initiate behaviors',
    population: 'Adults across health/goal domains',
    source: 'Gollwitzer & Sheeran, Advances in Experimental Social Psychology',
    url: 'https://doi.org/10.1016/S0065-2601(06)38002-1',
    year: 2006,
    strength: 'meta-analysis',
    usedFor: 'Action copy is phrased as concrete when-where-how plans',
  },
  {
    id: 'one-habit-at-a-time',
    domain: 'Behavior change',
    claim: 'The dose-response of behavior-change advice is an inverted U — a moderate number of asks beats many.',
    numbers: '~2–3 simultaneous recommendations optimal for lifestyle change (150 intervention reports); just 1 for alcohol reduction',
    population: 'Health-behavior intervention meta-analysis',
    source: 'Wilson et al., Annals of Behavioral Medicine',
    url: 'https://pubmed.ncbi.nlm.nih.gov/25998235/',
    year: 2015,
    strength: 'meta-analysis',
    usedFor: 'Caps how many NEW habits the recommender pushes at once',
  },
  {
    id: 'fresh-start',
    domain: 'Behavior change',
    claim: 'Temporal landmarks boost goal starts measurably.',
    numbers: 'Gym visits +33% at a new week, +14% at a new month, +47% at a new semester; "diet" searches spike at landmarks',
    population: 'Field data, US adults',
    source: 'Dai, Milkman & Riis, Management Science ("The Fresh Start Effect")',
    url: 'https://doi.org/10.1287/mnsc.2014.1901',
    year: 2014,
    strength: 'cohort',
    usedFor: 'Timing new-habit recommendations to Mondays/month starts',
  },
  {
    id: 'streak-recovery',
    domain: 'Behavior change',
    claim: 'Rewarding people for RETURNING after a missed day beat 53 other interventions in the largest exercise experiment ever run.',
    numbers: '61,293 gym members, 54 interventions; top performer: small bonus for coming back after a miss (+27% visits)',
    population: 'StepUp megastudy participants',
    source: 'Milkman et al., Nature',
    url: 'https://www.nature.com/articles/s41586-021-04128-4',
    year: 2021,
    strength: 'rct',
    usedFor: 'Broken streaks trigger encouragement, never guilt',
  },
  {
    id: 'loss-framing-steps',
    domain: 'Behavior change',
    claim: 'The same incentive works better framed as a loss than a gain for activity goals.',
    numbers: '7,000-step goal: achieved 45% of days with loss-framed incentive vs 35% gain-framed vs 30% control',
    population: 'Adults with overweight/obesity, 13-week RCT',
    source: 'Patel et al., Annals of Internal Medicine',
    url: 'https://www.acpjournals.org/doi/10.7326/M15-1635',
    year: 2016,
    strength: 'rct',
    usedFor: '"Keeps you on pace / protects your progress" phrasing of predictions',
  },
  {
    id: 'sdt-motivation',
    domain: 'Behavior change',
    claim: 'Autonomy-supportive coaching (rationale, choice, empathy) predicts lasting change; controlling language backfires.',
    numbers: '184 datasets: autonomy support → need satisfaction (β=.33–.47) → sustained behavior; autonomous motivation predicts long-term adherence',
    population: 'Self-determination theory meta-analysis',
    source: 'Ntoumanis et al., Health Psychology Review',
    url: 'https://www.tandfonline.com/doi/full/10.1080/17437199.2020.1718529',
    year: 2021,
    strength: 'meta-analysis',
    usedFor: 'Recommendations explain *why* and offer choices, never commands',
  },
  {
    id: 'flexibility-beats-routine',
    domain: 'Behavior change',
    claim: 'Rigidly scheduled habit windows underperform flexible ones.',
    numbers: 'Incentivizing gym visits only in a fixed 2h daily window produced fewer visits during AND after the program vs flexible-time incentives',
    population: '~2,500 adults, field experiment',
    source: 'Beshears et al., Nature Human Behaviour',
    url: 'https://www.nature.com/articles/s41562-021-01238-x',
    year: 2021,
    strength: 'rct',
    usedFor: 'Recommendations suggest windows, never mandate exact times',
  },

  // ── Chronotype & work ───────────────────────────────────────────────
  {
    id: 'chronotype-distribution',
    domain: 'Chronotype & work',
    claim: 'Chronotype is near-normally distributed (up to ~10h lark-to-owl spread), latest around age 19, advancing with age.',
    numbers: 'Peak lateness at ~18–19y; >50% of lifetime chronotype change happens between 15–25; sex difference crosses over ~age 40',
    population: 'MCTQ database, n>100,000',
    source: 'Roenneberg et al., Current Biology / MCTQ studies',
    url: 'https://pubmed.ncbi.nlm.nih.gov/15620199/',
    year: 2004,
    strength: 'cohort',
    usedFor: 'Chronotype as a first-class profile dimension; age-typical defaults',
  },
  {
    id: 'synchrony-effect',
    domain: 'Chronotype & work',
    claim: 'Cognitive performance peaks at chronotype-aligned times; the penalty for misalignment grows with age.',
    numbers: 'Synchrony effect present in ~83% of older-adult studies vs ~45% of young-adult studies; strongest for executive/inhibition tasks',
    population: 'Adults tested at aligned vs misaligned times',
    source: 'May & Hasher, Psychological Science review; Facer-Childs et al.',
    url: 'https://pubmed.ncbi.nlm.nih.gov/28903672/',
    year: 2017,
    strength: 'meta-analysis',
    usedFor: 'Deep-work window recommendations by chronotype (weighted more for older users)',
  },
  {
    id: 'social-jetlag',
    domain: 'Chronotype & work',
    claim: 'Social jetlag — the workday/free-day sleep-timing gap — carries a measurable metabolic cost per hour.',
    numbers: 'Each 1h of social jetlag ≈ 33% higher odds of overweight; ~2/3 of Western populations carry >1h',
    population: 'MCTQ cohort, n≈65,000',
    source: 'Roenneberg et al., Current Biology ("Social Jetlag and Obesity")',
    url: 'https://pubmed.ncbi.nlm.nih.gov/22578422/',
    year: 2012,
    strength: 'cohort',
    usedFor: 'Bedtime-consistency scoring; weekend-shift warnings',
  },
  {
    id: 'evening-type-risk',
    domain: 'Chronotype & work',
    claim: 'Evening types carry modestly higher diabetes and mortality risk — largely mediated by lifestyle, i.e. modifiable.',
    numbers: 'Definite evening vs morning: T2D OR ≈1.25 (UK Biobank); all-cause mortality HR 1.10 — attenuated when behavior is accounted for',
    population: '433,268 UK Biobank adults',
    source: 'Knutson & von Schantz, Chronobiology International',
    url: 'https://pubmed.ncbi.nlm.nih.gov/29642757/',
    year: 2018,
    strength: 'cohort',
    usedFor: 'Evening-type coaching targets behaviors, never chronotype change',
  },
  {
    id: 'shift-anchor-sleep',
    domain: 'Chronotype & work',
    claim: 'Shift workers do best with anchor sleep, planned pre-shift naps, and managed light exposure.',
    numbers: 'AASM conditionally recommends: pre-shift nap, bright light during shift, caffeine+light for sleepiness, fixed anchor-sleep window across on/off days',
    population: 'Night and rotating shift workers',
    source: 'AASM clinical practice guidance; Minors & Waterhouse anchor-sleep studies',
    url: 'https://sleepeducation.org/sleep-disorders/shift-work/',
    year: 2020,
    strength: 'guideline',
    usedFor: 'Shift-work persona: regularity scored against anchor windows, not clock bedtimes',
  },
  {
    id: 'night-shift-risk',
    domain: 'Chronotype & work',
    claim: 'Chronic night-shift work is classified as probably carcinogenic and raises cardiometabolic risk — countermeasures matter.',
    numbers: 'IARC Group 2A (reaffirmed 2019); strongest evidence for breast cancer, risk rising with duration/intensity of night work',
    population: 'Long-term night workers',
    source: 'IARC Monographs Vol. 124, The Lancet Oncology',
    url: 'https://www.thelancet.com/journals/lanonc/article/PIIS1470-2045(19)30455-3/fulltext',
    year: 2019,
    strength: 'guideline',
    usedFor: 'Why LifeOS weights shift-worker sleep/recovery coaching so heavily',
  },
  {
    id: 'new-parent-sleep',
    domain: 'Chronotype & work',
    claim: 'New-parent sleep collapses acutely, recovers in duration over ~3 months, but stays fragmented for years.',
    numbers: 'Mothers: ~4.4h/day in week 1 (vs 7.8h pre-pregnancy) → ~7.3h by weeks 8–13; longest unbroken stretch falls 5.6h → 2.2h',
    population: 'Postpartum cohort studies',
    source: 'Montgomery-Downs et al., American Journal of Obstetrics & Gynecology',
    url: 'https://pubmed.ncbi.nlm.nih.gov/20430367/',
    year: 2010,
    strength: 'cohort',
    usedFor: 'New-baby mode: harm-reduction targets, suppressed failure flags',
  },

  // ── Nutrition & substances ──────────────────────────────────────────
  {
    id: 'home-cooking',
    domain: 'Nutrition & substances',
    claim: 'Frequent home cooking tracks with better diet quality and lower adiposity.',
    numbers: 'Home-cooked >5×/wk vs <3×/wk: +62g fruit, +98g vegetables daily, 28% lower odds of overweight BMI',
    population: '11,396 UK adults (plus US NHANES analyses)',
    source: 'Mills et al., IJBNPA; Wolfson & Bleich, Public Health Nutrition',
    url: 'https://ijbnpa.biomedcentral.com/articles/10.1186/s12966-017-0567-y',
    year: 2017,
    strength: 'cohort',
    usedFor: 'Meal-prep recommendations and the meal-prep simulator scenario',
  },
  {
    id: 'ultra-processed-rct',
    domain: 'Nutrition & substances',
    claim: 'Ultra-processed diets cause increased ad-libitum intake and weight gain; risk scales with UPF share of diet.',
    numbers: '+508 kcal/day and +0.9kg in 2 weeks (RCT) · each +10% dietary UPF share ≈ +1.9% cardiovascular-event risk (cohorts)',
    population: '20 inpatient adults (RCT); large cohorts (dose-response)',
    source: 'Hall et al., Cell Metabolism; subsequent meta-analyses',
    url: 'https://www.cell.com/cell-metabolism/fulltext/S1550-4131(19)30248-7',
    year: 2019,
    strength: 'rct',
    usedFor: 'Takeout/nutrition scoring rationale',
  },
  {
    id: 'us-alcohol-guidelines',
    domain: 'Nutrition & substances',
    claim: 'Alcohol guidance is tightening worldwide and is sex-differentiated for physiological reasons.',
    numbers: 'Canada 2023: 1–2/wk low risk, 3–6 moderate, ≥7 increasingly high · WHO: no safe level (Group 1 carcinogen) · legacy US limits (≤2/day men, ≤1/day women) were dropped from the 2025–2030 Dietary Guidelines, which now advise drinking less is better · women reach higher BAC per dose (lower body water, ~59% of male gastric ADH activity)',
    population: 'Adults who drink',
    source: 'CCSA 2023; WHO 2023; HHS/USDA Dietary Guidelines 2025–2030; Frezza et al., NEJM',
    url: 'https://www.ccsa.ca/canadas-guidance-alcohol-and-health',
    year: 2025,
    strength: 'guideline',
    usedFor: 'Sex-specific weekly alcohol ceilings; conservative framing',
  },
  {
    id: 'alcohol-sleep',
    domain: 'Nutrition & substances',
    claim: 'Even 1–2 evening drinks measurably degrade sleep architecture and overnight recovery.',
    numbers: '1–2 drinks: −10–15 min REM, nocturnal HR +~3 bpm · HRV suppression scales from ~−3% (1 drink) to ~−15% (4+)',
    population: 'Adults, controlled + large wearable field studies',
    source: 'Pietilä et al., JMIR Mental Health (HRV field study)',
    url: 'https://mental.jmir.org/2018/1/e23/',
    year: 2018,
    strength: 'cohort',
    usedFor: 'Alcohol→recovery pattern probe priors and simulator effects',
  },
  {
    id: 'caffeine-timing',
    domain: 'Nutrition & substances',
    claim: 'Caffeine\'s ~5h half-life (varying 3–4× between people) pushes the evidence-based cutoff to ~9h before bed for a full dose.',
    numbers: 'Half-life ~5h (range 2–10h) · meta-analysis: avoid caffeine ≥8.8h pre-bed (217mg dose) · 400mg at 6h pre-bed cut sleep >1h (Drake RCT)',
    population: 'Adults, RCTs + 2023 meta-analysis',
    source: 'Gardiner et al., Sleep Medicine Reviews; Drake et al., JCSM',
    url: 'https://www.sciencedirect.com/science/article/pii/S1087079223000205',
    year: 2023,
    strength: 'meta-analysis',
    usedFor: 'Caffeine-cutoff recommendations relative to personal bedtime',
  },
  {
    id: 'protein-older-adults',
    domain: 'Nutrition & substances',
    claim: 'Older adults need more protein than the standard RDA to counter sarcopenia.',
    numbers: '1.0–1.2 g/kg/day healthy 65+ (vs 0.8 RDA) · 1.2–1.5 g/kg with illness · pair with resistance training',
    population: 'Adults 65+',
    source: 'PROT-AGE Study Group, JAMDA',
    url: 'https://pubmed.ncbi.nlm.nih.gov/23867520/',
    year: 2013,
    strength: 'guideline',
    usedFor: 'Nutrition emphasis for 65+ personas',
  },
  {
    id: 'hydration-myth',
    domain: 'Nutrition & substances',
    claim: 'The "8×8 glasses" rule isn\'t evidence-based; real adequate-intake figures are sex-differentiated and include food.',
    numbers: 'Adequate total water: ~3.7 L/day men, ~2.7 L/day women, from ALL beverages + food (~20% from food); thirst is an adequate guide for most',
    population: 'Healthy adults',
    source: 'National Academies of Sciences Dietary Reference Intakes',
    url: 'https://www.nationalacademies.org/news/2004/02/report-sets-dietary-intake-levels-for-water-salt-and-potassium',
    year: 2004,
    strength: 'guideline',
    usedFor: 'Myth-busting: LifeOS doesn\'t nag about arbitrary water counts',
  },

  // ── Goals & motivation ──────────────────────────────────────────────
  {
    id: 'goal-setting-theory',
    domain: 'Goals & motivation',
    claim: 'Specific AND difficult goals reliably beat vague "do your best" goals — as long as the person accepts them as attainable.',
    numbers: 'Higher performance in ~90% of studies; d = 0.42–0.80 across ~400 studies, 40,000+ participants',
    population: 'Lab and field studies across domains',
    source: 'Locke & Latham, American Psychologist ("Building a Practically Useful Theory of Goal Setting")',
    url: 'https://pubmed.ncbi.nlm.nih.gov/12237980/',
    year: 2002,
    strength: 'meta-analysis',
    usedFor: 'Goal targets must be specific + challenging; adaptive weekly micro-targets keep them attainable',
  },
  {
    id: 'progress-principle',
    domain: 'Goals & motivation',
    claim: 'Visible progress on meaningful work is the single strongest driver of daily motivation.',
    numbers: 'In ~12,000 diary entries, progress events were the top predictor of best-motivation days; setbacks hurt ~2–3× more than progress helped',
    population: '238 knowledge workers, diary study',
    source: 'Amabile & Kramer, "The Progress Principle" (Harvard Business Review)',
    url: 'https://hbr.org/2011/05/the-power-of-small-wins',
    year: 2011,
    strength: 'cohort',
    usedFor: 'Accomplishments feed, momentum indicator, and small-win framing',
  },
  {
    id: 'baseline-relative-scoring',
    domain: 'Goals & motivation',
    claim: 'Progress feedback framed against one\'s own baseline sustains motivation better than comparison to others or absolute standards.',
    numbers: 'Self-referenced (mastery) feedback predicts persistence and intrinsic motivation across meta-analyses; normative comparison helps only the top performers',
    population: 'Achievement-goal literature',
    source: 'Elliot & McGregor achievement goal framework; meta-analytic reviews',
    url: 'https://psycnet.apa.org/record/2001-16704-005',
    year: 2001,
    strength: 'meta-analysis',
    usedFor: 'Life Score measures pace against YOUR baseline→goal line, never against other users',
  },
  {
    id: 'planning-fallacy',
    domain: 'Goals & motivation',
    claim: 'People systematically underestimate how long goals take — outside-view forecasts from actual base rates are far more accurate.',
    numbers: 'Classic studies: <30% of students finished a thesis by their "realistic" estimate; base-rate (reference-class) forecasting removes most of the bias',
    population: 'Planning-fallacy literature',
    source: 'Kahneman & Tversky; Buehler et al., "Exploring the Planning Fallacy" (JPSP)',
    url: 'https://psycnet.apa.org/record/1994-00898-001',
    year: 1994,
    strength: 'rct',
    usedFor: 'Goal odds come from Monte Carlo on your OWN historical variability — an outside view by construction',
  },
{
    id: 'nature-dose',
    domain: 'Physical activity',
    claim: '≥120 minutes/week in nature is the threshold associated with good health and wellbeing.',
    numbers: '<120 min/wk: no benefit vs zero · ≥120: significant benefit · peak 200–300 min/wk · holds across age and illness groups',
    population: '19,806 UK adults',
    source: 'White et al., Scientific Reports',
    url: 'https://www.nature.com/articles/s41598-019-44097-3',
    year: 2019,
    strength: 'cohort',
    usedFor: 'Green-exercise recommendations for retired/flexible personas',
  },
];

export function cite(id: string): Citation {
  const c = RESEARCH.find((r) => r.id === id);
  if (!c) throw new Error(`Unknown citation: ${id}`);
  return c;
}
